version: '3.9'

services:
  mongo_db:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  server:
    container_name: server_container
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      MONGO_URI: mongodb://mongo_db:27017
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
